Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [
    path('', views.aboutus, name='aboutus'),
    # Add more URL patterns as needed
]

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/base/urls.py
from django.contrib import admin
from django.urls import path ,include
from .views import authView,home
urlpatterns = [
    path("",home, name = "home"), 
    path("signup/",authView,name="authView"),
    path("accounts/", include("django.contrib.auth.urls")),
]

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/car_rental_app/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(("base.urls","base"),"base")),
    path('cars/', include('cars.urls')),
    path('aboutus/', include('aboutus.urls')),

] + static(settings.STATIC_URL)

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/cars/urls.py
# cars/urls.py

from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.available_cars, name='available_cars'),
    # Add more URL patterns as needed
]

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/base/models.py
from django.db import models

# Create your models here.

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/cars/models.py
from django.db import models

class Car(models.Model):
    model = models.CharField(max_length=100)
    year = models.IntegerField()
    availability = models.BooleanField(default=True)  # True if available, False if not available
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='car_images/')

    # Explicitly include the id field
    car_id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.model

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/aboutus/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def aboutus(request):
    return render(request, "aboutus/aboutus.html")

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/base/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request,"home.html",)

def authView(request):
    if request.method =="POST":
        form=UserCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
    else:
        form=UserCreationForm()
    return render(request,"registration/signup.html",{"form":form})

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/cars/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def available_cars(request):
    return render(request, "cars/cars.html")

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/templates/aboutus/aboutus.html
{% block content %}

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Rentals - Home</title>
    <!-- Link to your CSS file -->
    <link rel="stylesheet" href="{% static 'css/home/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/cars/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-x0F2X2nQF4m2jV/1AE5wz6hy0nTh0T0ub+wfXmG4B6Bd1Jd8BKNZPIsjeNUTr1sUdMOqG73mCmTOiyFxKHsZLg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <style>
        .carousel-item img {
            max-height: 400px; /* Adjust the max height as needed */
            width: auto; /* Ensures the width adjusts proportionally */
        }
    </style>
</head>

<body >
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <!-- Logo and Company Name -->
                <a class="navbar-brand" href="#">
                    <img src="/static/img/logo.png" class="rounded-circle" alt="Car Rentals Logo" height="40">
                    <!-- Sample Logo -->
                    Car Rentals
                </a>
                <!-- Toggle Button -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Navigation Links -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <!-- Move navigation links to the right -->
                        <li class="nav-item mx-2">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url "cars:available_cars" %}">Available Cars</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url "aboutus:aboutus" %}">AboutUs</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="btn btn-outline-primary" href="{% url "base:logout" %}">logout</a>                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="about" id="about">
            <div class="heading">
                <span>About Us</span>
                <h1>Best Customer Experience</h1>
            </div>
            <div class="about-container">
                <div class="about-img">
                    <img src="https://rukminim2.flixcart.com/image/850/1000/xif0q/poster/u/s/n/small-spos14252-poster-dodge-challenger-srt-demon-vehicle-car-original-imagkb9a8scmvp4k.jpeg?q=20&crop=false" alt="">
                </div>
                <div class="about-text">
                    <span>About Us</span>
                    <p>At Royal Cars pvt.ltd, we are driven by a passion for providing unparalleled travel experiences on wheels. As a leading car rental service, we pride ourselves on delivering exceptional service.</p>
                    <p>A diverse fleet of vehicles, and a seamless booking process. With us, your journey begins the moment you step into one of our meticulously maintained cars. Our team is dedicated to making your travel dreams a reality. Whether you're embarking on a road trip, exploring a new city, or simply need a reliable vehicle for your daily commute?.</p>
                    <a href="#" class="btn">Learn More</a>
                </div>
            </div>
         </section>
</body>

</html>


{% endblock content %}

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Login</title>
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700&display=swap" rel="stylesheet">
 {% load static %}
 <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body style="background-image:/static/img/home/bg.png">
  {% block content %}{% endblock content %}
</body>
</html>
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Registration Demo</title>
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700&display=swap" rel="stylesheet">
 <!-- Link to your CSS file -->
    <link rel="stylesheet" href="{% static 'css/home/style.css' %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-x0F2X2nQF4m2jV/1AE5wz6hy0nTh0T0ub+wfXmG4B6Bd1Jd8BKNZPIsjeNUTr1sUdMOqG73mCmTOiyFxKHsZLg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <style>
        .carousel-item img {
            max-height: 400px; /* Adjust the max height as needed */
            width: auto; /* Ensures the width adjusts proportionally */
        }
    </style>
</head>
<bodystyle="background-image: url('/static/img/home/bg.png');">

</body>
</html>

Car Rentals Application with Django Framework - Mohammad Rafee(422721104026-VRSCET)/Project/car_rental_app/templates/cars/cars.html
{% block content %}

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Rentals - Home</title>
    <!-- Link to your CSS file -->
    <link rel="stylesheet" href="{% static 'css/cars/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-x0F2X2nQF4m2jV/1AE5wz6hy0nTh0T0ub+wfXmG4B6Bd1Jd8BKNZPIsjeNUTr1sUdMOqG73mCmTOiyFxKHsZLg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <style>
        .carousel-item img {
            max-height: 400px; /* Adjust the max height as needed */
            width: auto; /* Ensures the width adjusts proportionally */
        }
    </style>
</head>

<body >
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <!-- Logo and Company Name -->
                <a class="navbar-brand" href="#">
                    <img src="/static/img/logo.png" class="rounded-circle" alt="Car Rentals Logo" height="40">
                    <!-- Sample Logo -->
                    Car Rentals
                </a>
                <!-- Toggle Button -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Navigation Links -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <!-- Move navigation links to the right -->
                        <li class="nav-item mx-2">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url "cars:available_cars" %}">Available Cars</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url "aboutus:aboutus" %}">AboutUs</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="btn btn-outline-primary" href="{% url "base:logout" %}">logout</a>                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    
         <!--Services-->
         <section class="services" id="services">
            <div class="heading">
                <span>Best Services</span>
                <h1>Explore Out Top Deals <br> From Top Rated Dealers</h1>
            </div>
            <div class="services-container">
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car1.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car2.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car3.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car4.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car5.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car6.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car7.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car8.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car9.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car10.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car11.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
    
                <div class="box">
                    <div class="box-img">
                        <img src="/static/img/cars/car12.jpg" alt="">
                    </div>
                    <p>2017</p>
                    <h3>2018 Honda Civic</h3>
                    <h2>$58500 | $358</h2>
                    <a href="#" class="btn">Rent Now</a>
                </div>
            </div>
         </section>
    
         <footer>
            <div class="container">
                <div class="row">
                      <div class="col" id="company">
                          <img src="img/jeep.png" alt="" class="logo">
                          <p>
                            We are specialized in renting a car, book your car of any brand.
                            Try our reliable services.
                          </p>
                          <div class="social">
                            <a href="#"><i class="fab fa-facebook"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-youtube"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin"></i></a>
                          </div>
                      </div>
    
    
                      <div class="col" id="services">
                         <h3>Services</h3>
                         <div class="links">
                            <a href="#">Top Deals</a>
                            <a href="#">All Cars</a>
                            <a href="#">Rent Car</a>
                            <a href="#">Brands</a>
                         </div>
                      </div>
    
                      <div class="col" id="useful-links">
                         <h3>Links</h3>
                         <div class="links">
                            <a href="about.html">About</a>
                            <a href="services.html">Services</a>
                            <a href="#">Our Policy</a>
                            <a href="#">Help</a>
                         </div>
                      </div>
    
                      <div class="col" id="contact">
                          <h3>Contact</h3>
                          <div class="contact-details">
                             <i class="fa fa-location"></i>
                             <p>HN-41, Iqbaltn Avenue, <br> LA, PAK</p>
                          </div>
                          <div class="contact-details">
                             <i class="fa fa-phone"></i>
                             <p>+92-313112185924</p>
                          </div>
                      </div>
                </div>
    
                <div class="row">
                      <div class="form">
                        <form action="">
                            <input type="text" placeholder="Email here...">
                            <button><i class="fa fa-paper-plane"></i></button>
                        </form>
                      </div>
                </div>
    
            </div>
         </footer>
    
        <!--ScrollReveal-->
    <script src="https://unpkg.com/scrollreveal"></script>
    
    
        <script src="main.js"></script>
</body>

</html>


{% endblock content %}